controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

    
delete_tarifs:
    path: /deleteTarifs
    controller: 'App\Controller\YourController::deleteTarif'
    methods: ['POST']